config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  root "books#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :books
  resources :user_books, only: [:create, :index, :show] do
    collection do
      delete :destroy
    end
  end
  resources :readthroughs, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_books, dependent: :destroy
  has_many :users, through: :user_books
  has_one_attached :cover_image
  validates :title, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/readthrough.rb
class Readthrough < ApplicationRecord
  after_initialize :set_default_start_date

  belongs_to :user_book

  private

  def set_default_start_date
    self.start_date ||= Date.today if new_record?
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  has_many :user_books, dependent: :destroy
  has_many :books, through: :user_books
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :readthroughs

  validates :user_id, uniqueness: { scope: :book_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  def index
    @books = Book.all
    @user_books = Current.user.books
  end

  def show

  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end
    
    def book_params
      params.expect(book: [ :title, :cover_image, :first_page, :last_page ])
    end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/readthroughs_controller.rb
class ReadthroughsController < ApplicationController
  def new
    @readthrough = Readthrough.new(user_book_id: params[:user_book_id])
  end

  def create
    @readthrough = Readthrough.new(readthrough_params)
    if @readthrough.save
      redirect_to @readthrough.user_book
    else 
      render :new, status: :unprocessable_entity 
    end
  end


  private

  def readthrough_params
    params.expect(readthrough: [ :start_date, :end_date, :user_book_id ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  def index
    @user_books = Current.user.user_books
  end

  def show
    @user_book = UserBook.find(params[:id])
  end

  def create
    book = Book.find(params[:book_id])
    user = Current.user
    user.books << book

    redirect_back fallback_location: books_path
  end

  def destroy
    user_book = Current.user.user_books.find_by(book_id: params[:book_id]) 
    user_book.destroy

    redirect_back fallback_location: books_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/readthrough_helper.rb
module ReadthroughHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :first_page %>
    <%= form.text_field :first_page %>
  </div>
  <div>
    <%= form.label :last_page %>
    <%= form.text_field :last_page %>
  </div>
  

  <div>
    <%= form.label :cover_image, style: "display: block" %>
    <%= form.file_field :cover_image, accept: "image/*" %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/books/edit.html.erb
<h1> Edit Book</h1>

<%= render 'form', book: @book %>
<%= link_to 'Cancel', @book %>

app/views/books/index.html.erb
<h1>Books</h1>

<%= link_to "My Books", user_books_path %>
<%= link_to "New book", new_book_path %>

<div id="books">
  <% @books.each do |book| %>
    <div>
      <%= link_to book.title, book %>-
      <% if @user_books.include?(book) %>
        <%= link_to "Destroy",
          user_books_path(book_id: book.id),
          data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "Add", 
          user_books_path(book_id: book.id),
          data: { turbo_method: :post } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>
<%= link_to 'Cancel', books_path %>

app/views/books/show.html.erb
<section class="book">
  <%= image_tag @book.cover_image if @book.cover_image.attached? %>
</section>
<h1><%= @book.title %></h1>
<div><b>First Page:</b> <%= @book.first_page %></div>
<div><b>Last Page:</b> <%= @book.last_page %></div>
<div><b>Total Pages:</b> <%= @book.last_page - @book.first_page %></div>
<%= link_to "Back", books_path %>
<%= link_to "Edit", edit_book_path(@book) %>
<%= button_to "Delete", @book, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bookstack" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Home", root_path %>
      <%= button_to "Logout", session_path, method: :delete if authenticated? %>
    </nav>
    <%= Current.user.email_address %>
    <%= yield %>
  </body>
</html>

app/views/readthroughs/new.html.erb
<h1>New Readthrough</h1>
<%= form_with model: @readthrough do |form| %>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>
  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>
  <div>
    <%= form.hidden_field :user_book_id, value: @readthrough.user_book_id %>
    <%= form.submit %>
  </div>
<% end %>
  

app/views/user_books/index.html.erb
<h1>My Books</h1>

<%= link_to "All Books", books_path %>

<div id="books">
  <% @user_books.each do |user_book| %>
    <div><%= link_to user_book.book.title, user_book %></div>
  <% end %>
</div>

app/views/user_books/show.html.erb
<h1><%= @user_book.book.title %></h1>
<%= link_to "Back", user_books_path %>

<h2>Readthroughs</h2>
<ul>
  <% @user_book.readthroughs.each do |readthrough| %>
    <li>
      <%= readthrough.id %>-
      <%= readthrough.start_date %>-
      <%= readthrough.end_date %>
    </li>
  <% end %>
  <li>
    <%= link_to "Start New Readthrough", new_readthrough_path(user_book_id: @user_book.id) %>
  </li>
</ul>